handler: numina
dataset_path: "AI-MO/NuminaMath-CoT"
dataset_source: default
dataset_split: train
question_key: problem
answer_key: solution
templating_parameters:
  template: "Return your final response within \\boxed{{}}. {prompt}"
