model_id: NovaSky-AI/Sky-T1-32B-Preview
llm_engine: vllm
accelerator_type: A100-80G
engine_kwargs:
  tensor_parallel_size: 2
  # pipeline_parallel_size: 1
  # max_num_seqs: 448
  # use_v2_block_manager: True
  # enable_prefix_caching: False
  # preemption_mode: "recompute"
  # block_size: 16
  # kv_cache_dtype: "auto"
  # enforce_eager: False
  gpu_memory_utilization: 0.9
  # enable_chunked_prefill: True
  # max_num_batched_tokens: 32768
  # max_seq_len_to_capture: 32768
runtime_env:
  env_vars:
    VLLM_ATTENTION_BACKEND: "FLASH_ATTN"
env_config:
  num_replicas: 4
  batch_size: 128
