dataset_name: "BAAI/TACO"
dataset_source: default
dataset_split: ALL
dataset_kwargs:
  trust_remote_code: true
templating_parameters:
  initial_template: "\nQUESTION:\n{prompt}"
  # Add starter code to initial template
  starter_code_template: "{input}\n{starter_code}"
  # stdin template is used when there is no starter code or fn_name
  stdin_template: "{input}\nUse Standard Input format\nANSWER:\n"
  # call template is used when there is starter code or fn_name
  call_template: "{input}\nUse Call-Based format\nANSWER:\n"

